### ISSUE TITLE
Dataset spliting

### ISSUE THREAD

**Issue by yjzhux** [rxtan2/DIDAN#2]
How do you split the dataset to 'train', 'valid' and 'test'? Thanks.
https://github.com/rxtan2/DIDAN/blob/a36dc632e21207d646413d883fcd3dc531c619fc/didan_train.py#L284-L286

**Comment by rxtan2** [comment]
We use 32000 articles in total where the first 30000 are for training, the subsequent 1000 for validation and the remaining for test.

**Comment by yjzhux** [comment]
@rxtan2 Noted with thanks.
